### ISSUE TITLE
How does `async` checkbox work?

### ISSUE THREAD

**Issue by kirbysayshi** [rd13/jsperf.app#16]
In jsperf classic, checking `async` would put a variable in scope that would signal when the async work was done: `deferred.resolve()`.

Although I do see the `async` value being saved in the DB, I don't see the `deferred` argument being placed in scope, which results in any async test silently failing and reporting all tests as successful.

But the console reveals:

<img width="1151" alt="Screenshot 2023-03-16 at 12 32 13 AM" src="https://user-images.githubusercontent.com/90831/225515130-45601acb-aab9-472d-a91b-8fd5539d2407.png">

A good example is here: https://jsperf.app/tofiho/3

**Comment by rd13** [comment]
@kirbysayshi Yes you are right, that was a typo on my part which I've just patched.
