### ISSUE TITLE
editing unpublished tests does not update

### ISSUE THREAD

**Issue by SpikedKira** [rd13/jsperf.app#9]
Changing the tests of an unpublished runner will change the tests on the client side but not the server side.  If you add an additional test it will show in the client but never leave "pending" state.  If you change the order of the first 2 tests it will run them in the original order and show reversed results.  This can lead to incorrect data collection.

**Comment by rd13** [comment]
@SpikedKira That's unusual - an unpublished runner should persist tests each time you edit them / add more tests. Once a runner is published you can't then edit those tests, instead it will create a new revision. Is this still not working as expected for you?

**Comment by SpikedKira** [comment]
yeah, it wasn't actually creating the revision and the URI was staying at `/1/`

**Comment by SpikedKira** [comment]
https://jsperf.app/puteta/1/preview
first creation was to log `1` and `2`
I ran once then hit "Edit"
changed values to log `3` and `4`
Run it again and it shows `console.log(3)` and `console.log(4)` on the screen, but console shows it logging `1` and `2`
url remains https://jsperf.app/puteta/1/preview after edit

**Comment by Craig-Macomber** [comment]
I think I hit the same issue. I have no interest in publishing results, I just want to try some things, and it just keeps giving me whatever the first version I tried was, and is not reflecting my changes. It shows my updated code, the but performance of it really seems like its running what ever was in there first.

**Comment by rd13** [comment]
@SpikedKira @Craig-Macomber - ah yes the previous tests were being cached. That's now been fixed thanks very much for pointing it out.
